### ISSUE TITLE
Add lines .locres

### ISSUE THREAD

**Issue by brtraducoes** [akintos/UnrealLocres#1]
Thank you very much!
Export and Import working, but I need to add lines!
I'm translating the game Partisans and the locres file in english is missing 4 lines!
In the Spanish file there are 4 lines in English no! Can you help me with this?

lines add

Key=A54CC5414B02B127EDA949B651C506AA=Obtain the intelligence data
Key=35C835324D21ADB455AAFA9CEAC25324=Investigate the crash site
Key=495586644EAE2896FFE42E885FB794D8=Story
Key=D4B4AB7849FBD04843660787FE16C5BA=Story

Link example files:
https://drive.google.com/file/d/1IP5rHW ... sp=sharing

**Comment by akintos** [comment]
I think it would be better to add "merge" function which merges two locres files and create a new one.
In your case, it should merge spanish locres file into english one, adding missing lines.
I will work on it.

**Comment by akintos** [comment]
Added merge command in version 1.1.0.

https://github.com/akintos/UnrealLocres/releases/tag/1.1.0
