### ISSUE TITLE
Import ".POT" not working.

### ISSUE THREAD

**Issue by brtraducoes** [akintos/UnrealLocres#2]
Hi, thank you so much, adding the lines!
But import .pot is not working, and if it is possible to extract in .json without csv.
It's very complicated to translate in csv!
Thanks!

example photo:

https://cdn.discordapp.com/attachments/547948170768809994/863173359318728744/unknown.png

https://cdn.discordapp.com/attachments/547948170768809994/863173633979187200/unknown.png

**Comment by akintos** [comment]
You should use `-f po` argument to import a po/pot file. In your screenshot, the program parsed the input translation file as a csv file.
I will consider adding a json converter in future, with format like this:
```json
[
  {
    "name": "",
    "strings": [
      {
        "key": "328FC0CE4222A3469E256B9C35DF4010",
        "source": "/ d",
        "target": ""
      },
      {
        "key": "B5958C8447CFE1243F9D84BF8411874B",
        "source": "weeks",
        "target": ""
      }
    ]
  },
  {
    "name": "ARTICY",
    "strings": [
      {
        "key": "DFr_C1B9DEC3_0x0100000F0000650D.Text",
        "source": "\"The world looks to you with hope. You have the power to defeat the invading hordes of German bandits.\"",
        "target": ""
      },
      {
        "key": "DFr_9B7285C4_0x0100001E00003FBD.Text",
        "source": "\"Come to Germany and help with the housework\". So that's what they call slavery now!",
        "target": ""
      }
    ]
  }
]
```

**Comment by Danteska** [comment]
Oh wow, I had this one too. Kind of assumed that it would recognize the file format when importing. But it does get solved with `-f po`.
