### ISSUE TITLE
Accents and other symbols do not get exported correctly

### ISSUE THREAD

**Issue by Danteska** [akintos/UnrealLocres#3]
Tried exporting a Spanish locres file to csv format.

> Exported 7745 strings to DNL.csv

Upon checking the file it has lines like this one:
"Content/261111412,Cabezal de bÃ¡culo: InvocaciÃ³n del SeÃ±or de los Espectros,"
which has broken accents and should be:
"Content/261111412,Cabezal de báculo: Invocación del Señor de los Espectros,"
(note how the letter ñ is not recognized properly either)

I'm not sure if it would show correctly when imported back again, but it's hard to work like this because I have to use the Search function a lot and it won't find "Cabezal de báculo" if it's showing "Cabezal de bÃ¡culo".

This file gets exported with correct encoding with other tools that do it in .txt format. Your tool is better because it shows actual content data, but it has this issue.

**Comment by brtraducoes** [comment]
It only works on unreal 4.20 to 4.26!
Post the locres file I see for you!

Game Partisans 

https://cdn.discordapp.com/attachments/547948170768809994/863248281345458196/unknown.png

All letter ok!

**Comment by akintos** [comment]
Can you upload the locres file?
UnrealLocres uses UTF-8 as default encoding, which Windows notepad does not prefer. Did you tried using Notepad++ or VSCode?

**Comment by Danteska** [comment]
jonastraducoes, my game executable file states UE 4.5.1.0.

akintos, you're correct, if opened with Notepad++ it's displayed correctly, the issue was with Excel because even Windows notepad has no issues with it. I'll upload the file just in case.
[DNL.zip](https://github.com/akintos/UnrealLocres/files/6795051/DNL.zip)

**Comment by brtraducoes** [comment]
hi, i don't know what the game is, but i did the test here and everything is fine with the tool!
The version of your game you look at the wrong .exe, well I find the right folder to look at!

example photo Unreal 4.24:
https://cdn.discordapp.com/attachments/547948170768809994/863373658956496906/unknown.png

use notepad++ always to edit texts!

Example photos:

Extract
https://cdn.discordapp.com/attachments/547948170768809994/863368603758886912/unknown.png

Edit = my name jonas
https://cdn.discordapp.com/attachments/547948170768809994/863371460855726094/unknown.png

opinion:
Use .pot format easier to edit

**Comment by Danteska** [comment]
> The version of your game you look at the wrong .exe, well I find the right folder to look at!

Yeah that's where I took the version from, it's correct  and 4.5.1 does exist :)

> hi, i don't know what the game is, but i did the test here and everything is fine with the tool!

I know, it's working correctly with Notepad++, so all good! The problem seems to be with Excel, not with the tool.

> Use .pot format easier to edit

what is the difference? I don't know this format.

**Comment by brtraducoes** [comment]
csv:
translator after the last ,
example photos:
https://cdn.discordapp.com/attachments/547948170768809994/863404798022909952/unknown.png

pot:
translator msgstr
example photos:
https://cdn.discordapp.com/attachments/547948170768809994/863405372680568842/unknown.png

"Yeah that's where I took the version from, it's correct and 4.5.1 does exist "
Must be modified, send a photo to see just for study!
