### ISSUE TITLE
Bright Memory Infinite Problem...

### ISSUE THREAD

**Issue by BoomBookTR** [akintos/UnrealLocres#5]
hi.
i used it for Bright Memory Infinite 15.11.2021 update and worked fine but today new update and no work.

new locres file is here.
[Game.locres.zip](https://github.com/akintos/UnrealLocres/files/7564318/Game.locres.zip)

maybe you can help me.
ty.

**Comment by akintos** [comment]
I can export and import the file you provided with no error. can you explain me which part is not working?

**Comment by BoomBookTR** [comment]
> I can export and import the file you provided with no error. can you explain me which part is not working?

game can't start.
so so so high ram usage...

**Comment by akintos** [comment]
I think the problem may not be related to this program? Export/import function is working just fine.

Try using [this tool](https://zenhax.com/viewtopic.php?f=17&t=13367) to change assets.

**Comment by BoomBookTR** [comment]
> I think the problem may not be related to this program? Export/import function is working just fine.
> 
> Try using [this tool](https://zenhax.com/viewtopic.php?f=17&t=13367) to replace Pak assets.

i extracted pak file and renamed file.pak-BAK.
after that again working fine.
your tool is working good.
there is quickbms problem.
