### ISSUE TITLE
Importing Issue

### ISSUE THREAD

**Issue by HarunErcan01** [akintos/UnrealLocres#6]
Hello, first of all, thank you for creating this tool.

I have an issue importing translated CSV file to LOCRES file. My command is:

`UnrealLocres.exe import "D:\Desktop\HARUN\Atolye\TTY\Cook\Game.locres" "D:\Desktop\HARUN\Atolye\TTY\Cook\Game.csv"`

and output message is:

```
D:\Desktop\HARUN\Atolye\TTY\Cook>UnrealLocres.exe import D:\Desktop\HARUN\Atolye\TTY\Cook\Game.locres D:\Desktop\HARUN\Atolye\TTY\Cook\Game.csv
UnrealLocres v1.1.0
https://github.com/akintos/UnrealLocres

Loaded D:\Desktop\HARUN\Atolye\TTY\Cook\Game.csv
Translated 0 / 3688 (%0,00)

Imported 0 translations.
Saved to D:\Desktop\HARUN\Atolye\TTY\Cook\Game.locres.new
```

So, new LOCRES file is same as the old one. What am I doing wrong?

Thanks

**Comment by akintos** [comment]
I guess you are **replacing** source(original) column text. This tool is designed to read target column text.

For example,

| key                               | source                | target |
|-----------------------------------|-----------------------|--------|
| /3BEC1370485E4844B1992795C12BA887 | Force Close All Doors |        |
| /A48CF8714ADE4C894FDDD2B61CC5743A | Force Open All Doors  |        |
| /2D0A10094F894D79F81E6A8FE91434F9 | Forgoe                |        |

if this is the original exported file, you should translate like below

| key                               | source                | target              |
|-----------------------------------|-----------------------|---------------------|
| /3BEC1370485E4844B1992795C12BA887 | Force Close All Doors | 모든 문 강제로 닫기 |
| /A48CF8714ADE4C894FDDD2B61CC5743A | Force Open All Doors  | 모든 문 강제로 열기 |
| /2D0A10094F894D79F81E6A8FE91434F9 | Formation             | 진형                |

You should use spreadsheet editor like Google Spreadsheet or Microsoft Excel to edit csv file, not the text editor.

**Comment by HarunErcan01** [comment]
Oh, got it, I will try and write the results here.

**Comment by HarunErcan01** [comment]
> I guess you are **replacing** source(original) column text. This tool is designed to read target column text.
> 
> For example,
> 
> key	source	target
> /3BEC1370485E4844B1992795C12BA887	Force Close All Doors	
> /A48CF8714ADE4C894FDDD2B61CC5743A	Force Open All Doors	
> /2D0A10094F894D79F81E6A8FE91434F9	Forgoe	
> if this is the original exported file, you should translate like below
> 
> key	source	target
> /3BEC1370485E4844B1992795C12BA887	Force Close All Doors	모든 문 강제로 닫기
> /A48CF8714ADE4C894FDDD2B61CC5743A	Force Open All Doors	모든 문 강제로 열기
> /2D0A10094F894D79F81E6A8FE91434F9	Formation	진형
> You should use spreadsheet editor like Google Spreadsheet or Microsoft Excel to edit csv file, not the text editor.

Tried and worked, thank you! I didn't realize at first that the filesystem works with the column system. As you said, I was trying to translate and import the original column text.

Thanks again.

**Comment by Fusseldieb** [comment]
> I guess you are **replacing** source(original) column text. This tool is designed to read target column text.
> 
> For example,
> 
> key	source	target
> /3BEC1370485E4844B1992795C12BA887	Force Close All Doors	
> /A48CF8714ADE4C894FDDD2B61CC5743A	Force Open All Doors	
> /2D0A10094F894D79F81E6A8FE91434F9	Forgoe	
> if this is the original exported file, you should translate like below
> 
> key	source	target
> /3BEC1370485E4844B1992795C12BA887	Force Close All Doors	모든 문 강제로 닫기
> /A48CF8714ADE4C894FDDD2B61CC5743A	Force Open All Doors	모든 문 강제로 열기
> /2D0A10094F894D79F81E6A8FE91434F9	Formation	진형

This is crucial information, and should therefore be mentioned in the README.md. I just tried for at least 30 min until realizing that I "might" be doing wrong...
