### ISSUE TITLE
Exporting issue

### ISSUE THREAD

**Issue by Xinacris** [akintos/UnrealLocres#7]
I got an error for reading out a .locres file as;

> Unhandled Exception: System.ArgumentOutOfRangeException: Non-negative number required.
> Parameter name: count
>    at System.IO.BinaryReader.ReadBytes(Int32 count)
>    at LocresLib.IO.BinaryReaderExtensions.ReadUnrealString(BinaryReader reader)
>    at LocresLib.LocresFile.Load(Stream stream)
>    at UnrealLocres.Program.ExportAndExit(ExportOptions opt)
>    at UnrealLocres.Program.Main(String[] args)

not sure why is this happening, any help?

**Comment by Xinacris** [comment]
And probably why is this happening is because game is chinese :')

**Comment by MalachiMassey** [comment]
I am also having this exact issue, also with a Chinese game. Apart from this issue this seems like one of the best .locres tools available. A quick fix would be greatly appreciated.

**Comment by akintos** [comment]
Can you please upload the locres file?

**Comment by MalachiMassey** [comment]
https://drive.google.com/file/d/1KV7H8oDmpiSydze7r5fUTfZJ_j29F7l1/view?usp=sharing

**Comment by akintos** [comment]
The file is either encrypted or compressed. What game is it?

**Comment by Xinacris** [comment]
I believe we have the same job, the game's name is Nightmare Breaker, a chinese mmorpg I believe.

**Comment by akintos** [comment]
Many online games use additional encryption over Unreal Engine's default encryption to protect their assets and prvent cheating.
Anyway, I think this is not an issue of this project, closing.
